/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#353535',
        'secondary-container': '#454747',
        secondary: '#c6c6c7',
        'on-error-container': '#ffdad6',
        tertiary: '#f8f4f4',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        primary: '#fff5dc',
        'on-tertiary-container': '#5f5e5e',
        'secondary-fixed-dim': '#c6c6c7',
        'primary-fixed': '#ffe170',
        'error-container': '#93000a',
        'outline-variant': '#4d4632',
        'on-tertiary-fixed-variant': '#474746',
        'surface-tint': '#e9c400',
        'on-secondary-container': '#b4b5b5',
        'on-tertiary-fixed': '#1c1b1b',
        'secondary-fixed': '#e2e2e2',
        'on-primary-fixed': '#221b00',
        outline: '#999077',
        surface: '#131313',
        'on-surface-variant': '#d0c6ab',
        'inverse-on-surface': '#303030',
        'on-primary-container': '#705d00',
        'on-tertiary': '#313030',
        'on-primary-fixed-variant': '#544600',
        'surface-container-high': '#2a2a2a',
        background: '#131313',
        'primary-container': '#ffd600',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-highest': '#353535',
        error: '#ffb4ab',
        'tertiary-fixed': '#e5e2e1',
        'surface-container': '#1f1f1f',
        'tertiary-container': '#dbd8d8',
        'on-primary': '#3a3000',
        'on-secondary': '#2f3131',
        'on-secondary-fixed-variant': '#454747',
        'tertiary-fixed-dim': '#c8c6c5',
        'primary-fixed-dim': '#e9c400',
        'on-surface': '#e2e2e2',
        'on-secondary-fixed': '#1a1c1c',
        'inverse-primary': '#705d00',
        'on-error': '#690005',
        'inverse-surface': '#e2e2e2',
        'on-background': '#e2e2e2',
        'surface-container-low': '#1b1b1b',
      },
      borderRadius: {
        DEFAULT: '20px',
        lg: '20px',
        xl: '20px',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        'stack-lg': '40px',
        'margin-mobile': '24px',
        'stack-sm': '8px',
        gutter: '32px',
        'section-gap': '160px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-caps': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '160%', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '150%', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '100%', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-xl': ['120px', { lineHeight: '110%', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['64px', { lineHeight: '115%', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '120%', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
};
